### ISSUE TITLE
Mind camera game delay insufficient

### ISSUE THREAD

**Issue by jwdunn1** [uvbakutan/enhance#1]
Perhaps my computer is too fast, or I am too slow, but all the circles appear at exactly the same time. I would expect the program to dynamically adapt to the user's response time (slow down or speed up) as appropriate. As it is, I am unable to pass level 3 and find this particular program unusable. Tested in Chrome Version 62.0.3202.89 and Firefox Version 56.0.2. System: Windows 7 on a Xeon W3520 (equivalent to i7 920 generation 1) overclocked to 3.37GHz with 12GB memory

**Comment by uvbakutan** [comment]
Thank you for submitting this issue. I was not able to recreate this behavior on 2 laptops and my phone. Do you have similar problems on the other games? All of them use the same delay logic.

**Comment by jwdunn1** [comment]
The other apps appear to work OK. I tested on three additional devices: Android phone (LG K10 running Android 7.0), iPhone 7 (iOS 11.1.1, Safari), and MacBook Air (macOS 10.13.1 ,Chrome and Safari). These also run the timers too fast. Here is what I am seeing: https://youtu.be/M_FOWx91nNI 

Animation is usually handled via requestAnimationFrame(), but without it perhaps the browser is updating canvas in one batch.

**Comment by uvbakutan** [comment]
Thank you for including the video. I think we have a misunderstanding on the game logic. At each level all the circles need to be drawn and the user needs to click only on the last one that appeared. If any of the old circles is clicked it will result in a game over an the correct circle will flash. At the beginning the game is quite easy but after reaching Level 20 it is much harder to notice which circle is the new one.

**Comment by jwdunn1** [comment]
Well, that explains it! Thanks.
